In [1]:
import numpy as np

In [4]:
arr=[1,2,3,43,2]
arr=np.array(arr)
print(arr)

[ 1  2  3 43  2]


In [21]:
print("whats is up")
np.__version__

whats is up


'1.18.5'

In [7]:
a=np.array([12,34,32,54,64,4])

In [8]:
a

array([12, 34, 32, 54, 64,  4])

In [9]:
for i in a:
    print(i)

12
34
32
54
64
4


In [13]:
a[6]=43

IndexError: index 6 is out of bounds for axis 0 with size 6

In [14]:
a

array([12, 34, 32, 54, 64,  4])

In [15]:
a[2:]

array([32, 54, 64,  4])

In [20]:
a[:]

array([12, 34, 32, 54, 64,  4])

In [17]:
a[:-1]

array([12, 34, 32, 54, 64])

In [22]:
# you can create numpy array from list , tuple 
arr=np.array([10,20,30])

In [23]:
arr

array([10, 20, 30])

In [26]:
print(type(arr))
# there is cllass called ndarray and arr is the object of that class 

<class 'numpy.ndarray'>


In [28]:
arr1=np.array([10,20.4,435])
print(arr1)
# as list can contains hetrogenous elements what numpy array does is it infer (the best suitable type for the values)the values 
arr1=np.array([12,45,34.3,'hello'])
print(arr1) # as ypu can see the all values have been inferd i.e changed to string type , such arrays are not useful as we cannot poerform much of operations in them



[ 10.   20.4 435. ]


array(['12', '45', '34.3', 'hello'], dtype='<U32')

In [30]:
arr1=np.array([12,45,34.3,'hello'],dtype=np.int)
# what happen here is you have mention the datatype of the numpy array using argument called dtype=np.int  as 'hello' is a string it throws error

ValueError: invalid literal for int() with base 10: 'hello'

In [31]:
arr1=np.array([12,45,34.3,-34],dtype=np.int32)
print(arr1)

[ 12  45  34 -34]


In [33]:
arr1=np.array([12,45,34.3,-34],dtype=np.uint32)
print(arr1)

[        12         45         34 4294967262]


In [38]:
# creating a numpy array by not using existing list 
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
l=list(range(50))
arr=np.arange(50)

In [37]:
import sys

In [45]:
print(sys.getsizeof(l))
print(sys.getsizeof(a))
# As you can see numpy array takes less memory than list therefore numpy array is prefered 


456
120


In [51]:
# one more way of creating arrays 
a=np.zeros((10),dtype=np.int) # takes a tuple as a argument as a size of the numpy array
# initialize every element with zero
print(a) # you can intialize the float or int type values by providing the dtype 

[0 0 0 0 0 0 0 0 0 0]


In [50]:
# another way of creating numpy arrays
np.ones((10),dtype=np.int)
# intializes each values with value 1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
np.full((10),3)
# a numpy array is created of size 10 with intial value 3 

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [54]:
np.random.random(size=(10)) # creates a numpy array [0,1)

array([0.17784762, 0.12688876, 0.04905017, 0.46511535, 0.93765659,
       0.98018025, 0.26633609, 0.6015484 , 0.13487748, 0.85850117])

In [55]:
# another way of creating numpy array 
np.random.randint(2,560,size=10) # creating a random array from low to high and of what size 
    # in the given code the array takes 10 elements from 2 to 560

array([250,  88, 181,  98, 314, 222,   2, 499,  72, 133])

In [56]:
# another way of creating a numpy array 
np.random.uniform(low =32,high = 483,size=10)
# creating a numpy array which contans floating point numbers from 32 to 483 with size of the numpy array is 10 

array([ 46.48593543, 326.40366625, 115.8077649 ,  72.10783749,
        71.83792161, 419.91346084, 369.660231  , 252.29924408,
       434.21292   , 378.4755103 ])

In [57]:
# creating a numpy array 
np.linspace(2,50,10)
# in which we want starting element as 2 and element as 40 with equal interval between them 

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

# Creation of 2D array 

In [62]:
a=np.array([[1,2,3],[45,32,7],[23,4,322]])
print(a)

[[  1   2   3]
 [ 45  32   7]
 [ 23   4 322]]


In [64]:
# creating numpy 2d array from zeros function
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
# creating numpy 2d array from ones function
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
# creating numpy 2d array from full function 
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [68]:
# when you have to randomly intialize a 2d array 
np.random.randint(3,100,size=(3,4))

array([[54, 30, 14, 79],
       [47, 93, 64, 15],
       [67, 11, 62,  4]])

In [69]:
# creating a random 2d array with floating point values 
np.random.uniform(3,100,(3,4))

array([[47.17506989, 37.96304158, 81.37314089, 91.44147246],
       [87.15210713, 80.76575597, 23.51520122, 55.00249629],
       [10.77081305, 33.02192979, 47.58115699, 83.45314923]])

In [75]:
# creating a 3d array 
np.random.randint(3,100,size=(4,3,4))


array([[[72, 89, 71, 61],
        [71, 14,  7, 43],
        [91, 22, 53, 93]],

       [[35, 40, 31, 29],
        [93, 54, 99, 71],
        [98, 68, 16, 30]],

       [[65, 47, 96, 13],
        [56, 56, 47, 40],
        [54, 94, 18, 36]],

       [[78, 73, 86, 37],
        [93, 64, 13, 88],
        [81, 29,  8,  8]]])