In [2]:
import numpy as np

In [3]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# changing the size of the numpy array 
a.reshape((4,3),) # what reshape does is it does not make changes in the oriinal array but creates a new array 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a.reshape((4,2)) # it throws error 

ValueError: cannot reshape array of size 12 into shape (4,2)

In [7]:
# but if we use -1 as the column value then 
a.reshape((4,-1))
# what it does is finds the no. of columns on its own 


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a.reshape((5,-1))
# it thorws error becuase what ever you multiply with 5 we will not get 12 


ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [9]:
a.reshape((3,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [10]:
# with  the help of resize method we can resize a numpy array
a.resize((4,3))
# as you can see nothing has returned as what resize does is it chenges the dimension of the original numpy array 
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
# in resize negative dimebsioning is not allowed 
a.resize((4,-1))
# no facility to infer

ValueError: negative dimensions not allowed

In [12]:
a.resize(4,5,refcheck=False)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [20]:
print(np.resize(a,(6,6)))
a

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  0  0  0  0  0]
 [ 0  0  0  1  2  3]
 [ 4  5  6  7  8  9]
 [10 11  0  0  0  0]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [19]:
#converting a 2d array into 1d array 
a.flatten('F') # column major 
# use order='C' for row major

array([ 0,  5, 10,  0,  1,  6, 11,  0,  2,  7,  0,  0,  3,  8,  0,  0,  4,
        9,  0,  0])

In [21]:
# numpy as a function that works exactly like flattern
np.ravel(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  0,  0,  0,  0,
        0,  0,  0])

In [23]:
# concatinate two arrays 
a=np.arange(3)
b=np.arange(3)
np.concatenate((a,b))

array([0, 1, 2, 0, 1, 2])

In [30]:
# concatenating 2 2d arrays
a=np.arange(12).reshape(3,4)
b=np.random.randint(10,23,size=12).reshape(3,4)
np.concatenate((a,b),axis=1)
# if you want to concatenate the arrays in column major use axis argument = 1

array([[ 0,  1,  2,  3, 21, 15, 20, 16],
       [ 4,  5,  6,  7, 12, 13, 12, 10],
       [ 8,  9, 10, 11, 15, 20, 10, 17]])

In [31]:
a=np.arange(12).reshape(3,4)
b=np.random.randint(10,23,size=12).reshape(3,4)
np.concatenate((a,b),axis=0)
# if you want to concatenate the arrays in row major use axis argument = 0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 12, 18, 19],
       [10, 13, 15, 22],
       [22, 11, 15, 19]])

In [32]:
# IF we do axis = None , then , what it does is flatterns the 2d arrays and make them into 1d array and then concatenate
a=np.arange(12).reshape(3,4)
b=np.random.randint(10,23,size=12).reshape(3,4)
np.concatenate((a,b),axis=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 18, 21, 16, 10, 17,
       11, 21, 15, 22, 13, 19, 21])

In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
b

array([[18, 21, 16, 10],
       [17, 11, 21, 15],
       [22, 13, 19, 21]])

In [36]:
np.hstack((a,b)) # adds the next 2d array column wise

array([[ 0,  1,  2,  3, 18, 21, 16, 10],
       [ 4,  5,  6,  7, 17, 11, 21, 15],
       [ 8,  9, 10, 11, 22, 13, 19, 21]])

In [37]:
np.vstack((a,b)) # adds the next 2d array row wise 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [18, 21, 16, 10],
       [17, 11, 21, 15],
       [22, 13, 19, 21]])

In [38]:
# Performing airthmetic operations on array 
a=np.arange(5)
print(a)
# scalar airthmetic
a*2

[0 1 2 3 4]


array([0, 2, 4, 6, 8])

In [40]:
print(a+2)
print(a-2)
print(a/2)

[2 3 4 5 6]
[-2 -1  0  1  2]
[0.  0.5 1.  1.5 2. ]


In [44]:
# vector airthmetic 
# when 2 with same postion perform airthmetic
b=np.arange(5,10)
print(a*b)
print(a-b)
print(a/b)
print(a+b)

[ 0  6 14 24 36]
[-5 -5 -5 -5 -5]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[ 5  7  9 11 13]


In [46]:
a=np.arange(6).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
a+2

array([[2, 3, 4],
       [5, 6, 7]])

In [48]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
b=np.random.randint(10,20,size=(2,3))

In [50]:
b

array([[17, 13, 15],
       [19, 12, 12]])

In [51]:
a*b # performs multiplication position by position , element by element 

array([[ 0, 13, 30],
       [57, 48, 60]])

In [55]:
# dot product 
b=np.random.randint(10,20,size=(3,3))
print(b)
np.dot(a,b)

[[15 11 15]
 [10 19 11]
 [14 17 14]]


array([[ 38,  53,  39],
       [155, 194, 159]])

In [56]:
a@b # @ performs dot multiplications 


array([[ 38,  53,  39],
       [155, 194, 159]])

In [58]:
a=np.arange(6)
print(a)
np.square(a)
# also works for list and tuple 
print(np.square([1,2,3,4,5,6]))
print(np.square((1,2,4,3,6,5)))

[0 1 2 3 4 5]
[ 1  4  9 16 25 36]
[ 1  4 16  9 36 25]


In [59]:
# for finding square root
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [68]:
a=np.random.randint(10,100,10)
a

array([60, 98, 42, 36, 60, 14, 39, 77, 49, 85])

In [69]:
print(np.min(a)) # finds the smallest element in the array 
print(np.argmin(a)) # finds the smallest elements index in the array 
print(np.max(a)) # finds the largest element in the array 
print(np.argmax(a)) # finds the index of the largest element in the array 
print(np.sum(a)) # sum of all the elements inside the array 
print(np.mean(a)) # by default it calculates the airthmetic mean 
print(np.median(a)) # finds the median inside the array 
print(np.quantile(a,q=[.25,.5,.75]))

14
5
98
1
560
56.0
54.5
[39.75 54.5  72.75]


In [73]:
arr=np.random.randint(10,100,size=(3,4))
print(arr)

[[33 52 11 29]
 [97 56 51 42]
 [67 94 62 93]]


In [78]:
print(np.sum(arr))
print(np.sum(arr,axis=1)) # row major sum 
print(np.sum(arr,axis=0)) # column major sum 
print(np.mean(arr,axis=1)) # row wise sum 
print(np.mean(arr,axis=0)) # column wise mean 

687
[125 246 316]
[197 202 124 164]
[31.25 61.5  79.  ]
[65.66666667 67.33333333 41.33333333 54.66666667]


In [84]:
print(arr.ndim) # tells the dimension of the array
print(arr.size) # tells the total elements inside the array 
print(arr.shape) # tells how many row and column does the array have and returns it in a tuple
print(arr.shape[0])
print(arr.dtype) # tells the datatype of the elements that it contain 

2
12
(3, 4)
3
int32


In [85]:
# slicing inside a array 
a=np.random.randint(10,100,size=(10,10))
print(a)

[[87 23 95 69 38 50 54 37 36 32]
 [20 36 84 34 50 62 11 88 79 13]
 [75 28 67 96 76 15 85 39 42 45]
 [60 89 10 12 41 84 69 21 31 65]
 [44 85 41 51 60 59 68 47 88 47]
 [46 32 50 60 68 75 12 89 67 93]
 [58 93 92 35 94 82 28 54 85 19]
 [29 58 70 25 43 17 22 64 32 93]
 [33 74 96 34 64 44 22 56 97 70]
 [46 26 30 64 65 94 39 28 39 99]]


In [86]:
a[0:2,3:5] 

array([[69, 38],
       [34, 50]])

In [89]:
# boolean slicing /condition slicing 
a[a>50]

array([87, 95, 69, 54, 84, 62, 88, 79, 75, 67, 96, 76, 85, 60, 89, 84, 69,
       65, 85, 51, 60, 59, 68, 88, 60, 68, 75, 89, 67, 93, 58, 93, 92, 94,
       82, 54, 85, 58, 70, 64, 93, 74, 96, 64, 56, 97, 70, 64, 65, 94, 99])

In [90]:
a[a%2==0] # return all the eeven numbers inside the array 

array([38, 50, 54, 36, 32, 20, 36, 84, 34, 50, 62, 88, 28, 96, 76, 42, 60,
       10, 12, 84, 44, 60, 68, 88, 46, 32, 50, 60, 68, 12, 58, 92, 94, 82,
       28, 54, 58, 70, 22, 64, 32, 74, 96, 34, 64, 44, 22, 56, 70, 46, 26,
       30, 64, 94, 28])

In [93]:
a[(a%2==0) & (a<50)] # slicing done with condition that number should be even and less than 50 

array([38, 36, 32, 20, 36, 34, 28, 42, 10, 12, 44, 46, 32, 12, 28, 22, 32,
       34, 44, 22, 46, 26, 30, 28])

In [94]:
a[(a%2==0) | (a<50)] # slicing done with condition that number should be even or less than 50 

array([23, 38, 50, 54, 37, 36, 32, 20, 36, 84, 34, 50, 62, 11, 88, 13, 28,
       96, 76, 15, 39, 42, 45, 60, 10, 12, 41, 84, 21, 31, 44, 41, 60, 68,
       47, 88, 47, 46, 32, 50, 60, 68, 12, 58, 92, 35, 94, 82, 28, 54, 19,
       29, 58, 70, 25, 43, 17, 22, 64, 32, 33, 74, 96, 34, 64, 44, 22, 56,
       70, 46, 26, 30, 64, 94, 39, 28, 39])

In [ ]:
a=np.loadtxt(,delattr=',') # converts a txt file into a numpy array 